# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5.0.0
      with:
        go-version: '1.20'

    - name: install mod
      run: go mod download

    - name: install wire
      run: go install github.com/google/wire/cmd/wire@latest

    - name: gen wire
      run: wire gen ./app

    - name: Build
      run: CGO_ENABLED=0 go build -ldflags "-s -w" -o ./app/bin/app ./app/cmd

